language: java

git:
  depth: 3

jdk:
  - oraclejdk8

services:
  - mysql
  
before_install: 
  - sudo rm /etc/mavenrc
  - export M2_HOME=/usr/local/maven
  - export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xms256m -Xmx512m"
    
before_script:
  - mysql -e 'create database hpdbweb;'
  - "echo $JAVA_OPTS"
  - "echo $MAVEN_OPTS"
  - ulimit -a
  - free -m

after_script:
  - ulimit -a
  - free -m

script: 
  - mvn clean install