language: java

git:
  depth: 3

jdk:
  - oraclejdk8

services:
  - mysql
  
before_script:
  - mysql -e 'create database hpdbweb;'
  - "export JAVA_OPTS=-Xmx512m"
 - "echo $JAVA_OPTS"

sudo: false
script: mvn clean install