language: java

git:
  depth: 3

jdk:
  - oraclejdk8

services:
  - mysql
  
before_script:
  - mysql -e 'create database hpdbweb;'
  - echo "MAVEN_OPTS='-Xmx1g -XX:MaxPermSize=512m'" > ~/.mavenrc  
  - "echo $JAVA_OPTS"
  - "echo $MAVEN_OPTS"

sudo: false
script: mvn clean install