version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - hpdb-data:/var/lib/mysql:delegated
      - ./mysql-dump:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  app:
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
      
networks:
  my-network:
    driver: bridge

volumes:
  hpdb-data:
