# overrides database credentials in jdbc.properties
apiVersion: v1
kind: Secret
metadata:
  name: hpdb-mysql-credentials
stringData:
  MARIADB_ROOT_PASSWORD: "rootpassword"
  MARIADB_USER: "hpdb_user"
  MARIADB_PASSWORD: "hpdbwebaafc1"
  MARIADB_DATABASE: "hpdbweb"

  # application runtime (mysql-compatible)
  MYSQL_USER: "hpdb_user"
  MYSQL_PASSWORD: "hpdbwebaafc1"
  MYSQL_DATABASE: "hpdbweb"

# Create this secret on openshift: 
# oc apply -f hpdb-secret.yaml
# Given that the secret's name matches the secret name used by the hpdb-db deployment, 
#  it will automatically apply to the deployment on the cluster once both are created on Openshift.
