apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpdb-db
  labels:
    app: hpdb
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpdb
      tier: database
  template:
    metadata:
      labels:
        app: hpdb
        tier: database
    spec:
      containers:
      - name: mysql
        image: {{ .Values.db.deployment.imageRepo }}:{{ .Values.db.deployment.imageTag }}
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: hpdb-mysql-credentials
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: hpdb-mysql-pvc
