apiVersion: v1
kind: Service
metadata:
  name: hpdb-db
  labels:
    app: hpdb
    tier: database
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    targetPort: 3306
  selector:
    app: hpdb
    tier: database
