apiVersion: v1
kind: Secret
metadata:
  name: hpdb-mysql-credentials
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "{{ randAlphaNum 32 }}"
  MYSQL_USER: "{{ .Values.db.secret.user }}"
  MYSQL_PASSWORD: "{{ .Values.db.secret.password }}"
  MYSQL_DATABASE: "{{ .Values.db.secret.database }}"
