apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secretName }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "{{ .Values.mysql.rootPassword }}"
  MARIADB_USER: "{{ .Values.mysql.user }}"
  MARIADB_PASSWORD: "{{ .Values.mysql.password }}"
  MARIADB_DATABASE: "{{ .Values.mysql.database }}"

  # application runtime (mysql-compatible)
  MYSQL_USER: "{{ .Values.mysql.user }}"
  MYSQL_PASSWORD: "{{ .Values.mysql.password }}"
  MYSQL_DATABASE: "{{ .Values.mysql.database }}"
