jdbc.driverClassName=org.mariadb.jdbc.Driver
jdbc.url=jdbc:mariadb://hpdb-db:3306/hpdbweb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
jdbc.username=hpdb_user
jdbc.password=hpdbwebaafc1
jdbc.validationQuery=${jdbc.validationQuery}

# hibernate.dialect=${hibernate.dialect}
hibernate.dialect=org.hibernate.dialect.MariaDB103Dialect

# Needed by Hibernate3 Maven Plugin defined in pom.xml
spring.jpa.hibernate.ddl-auto=none
hibernate.hbm2ddl.auto=none
# hibernate.connection.username=hpdb_user
hibernate.connection.password=hpdbwebaafc1
hibernate.connection.url=jdbc:mariadb://hpdb-db:3306/hpdbweb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
hibernate.connection.driver_class=${jdbc.driverClassName}
# make hibernate sure to be compatable with mariadb
hibernate.dialect=org.hibernate.dialect.MariaDB103Dialect